services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/hello-app:latest
    container_name: fast-api-prod
    ports:
      - "8000:8000"

    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /tmp
      - /run
    
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

    restart: unless-stopped