name: CI Non-Root PRO (Versioning & Push)

on:
  push:
    branches: [ "feature/docker-nonroot" ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5 # Aktualizacja do v5
        with:
          python-version: "3.11"
          cache: 'pip' # Cache dla pip (szybsze testy)
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Pytest
        run: pytest

  release-and-build:
    needs: unit-tests
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # NIEZBĘDNE DLA CACHE DOCKERA
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Non-Root Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/hello-nonroot:${{ steps.tag_version.outputs.new_tag }}
            ghcr.io/${{ github.repository_owner }}/hello-nonroot:latest
          # Pełne wykorzystanie cache'u GitHub Actions
          cache-from: type=gha
          cache-to: type=gha,mode=max