name: CI Distroless PRO (Versioning & Push)

on:
  push:
    branches: [ "feature/distroless-docker" ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip' # Magiczna linia dla Pythona
          
      - name: Install dependencies
        # Używamy requirements.txt, skoro już go odchudziliśmy
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pytest
        run: pytest

  release-and-build-distroless:
    needs: unit-tests
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # --- KLUCZOWE DLA CACHE DOCKERA ---
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: image=moby/buildkit:latest

      # 1. Wyliczanie wersji
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch

      # 2. Logowanie do GHCR
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3. Build i Push obrazu Distroless z pełnym cachem
      - name: Build and push Distroless Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Używamy Twojej nowej nazwy obrazu
          tags: |
            ghcr.io/${{ github.repository_owner }}/hello-distroless:${{ steps.tag_version.outputs.new_tag }}
            ghcr.io/${{ github.repository_owner }}/hello-distroless:latest
          # Te linie sprawią, że ponowny build po zmianie 1 linii kodu zajmie sekundy
          cache-from: type=gha
          cache-to: type=gha,mode=max